language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - gfortran
      - libblas-dev
install:
  - pip install --user numpy
script:
  - cargo build --verbose
  - RUST_BACKTRACE=1 cargo test -j1
